-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 13:09:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyPizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyPizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyPizzeria` DEFAULT CHARACTER SET utf8 ;
USE `MyPizzeria` ;

-- -----------------------------------------------------
-- Table `MyPizzeria`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`provinces` (
  `idprovinces` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovinces`),
  UNIQUE INDEX `provincescol_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`localities` (
  `idlocalities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`idlocalities`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `province_id_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `province_id`
    FOREIGN KEY (`province_id`)
    REFERENCES `MyPizzeria`.`provinces` (`idprovinces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`postalcodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`postalcodes` (
  `idpostalcodes` SMALLINT NOT NULL,
  `locality_id` INT NOT NULL,
  PRIMARY KEY (`idpostalcodes`),
  UNIQUE INDEX `idpostalcodes_UNIQUE` (`idpostalcodes` ASC) VISIBLE,
  INDEX `locality_id_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `locality_id`
    FOREIGN KEY (`locality_id`)
    REFERENCES `MyPizzeria`.`localities` (`idlocalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`products` (
  `idproducts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL COMMENT 'store the reference to the storage place of the image here.',
  `current_category_id` INT NULL COMMENT 'For exclusive use of those products that can have different categories, currently Pizza.',
  `price` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`order_products` (
  `idorder_products` INT NOT NULL AUTO_INCREMENT,
  `firstproduct_id` INT UNSIGNED NOT NULL,
  `secondproduct_id` INT UNSIGNED NOT NULL,
  `thirdproduct_id` INT UNSIGNED NOT NULL,
  `first_product_amount` TINYINT UNSIGNED NOT NULL,
  `second_product_amount` TINYINT UNSIGNED NOT NULL,
  `third_product_amount` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idorder_products`),
  INDEX `firstproduct_id_idx` (`firstproduct_id` ASC) VISIBLE,
  INDEX `secondproduct_id_idx` (`secondproduct_id` ASC) VISIBLE,
  INDEX `thirdproduct_id_idx` (`thirdproduct_id` ASC) VISIBLE,
  CONSTRAINT `firstproduct_id`
    FOREIGN KEY (`firstproduct_id`)
    REFERENCES `MyPizzeria`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `secondproduct_id`
    FOREIGN KEY (`secondproduct_id`)
    REFERENCES `MyPizzeria`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `thirdproduct_id`
    FOREIGN KEY (`thirdproduct_id`)
    REFERENCES `MyPizzeria`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`stores` (
  `idstores` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postal code` SMALLINT NOT NULL,
  PRIMARY KEY (`idstores`),
  INDEX `postalcode_id_idx` (`postal code` ASC) VISIBLE,
  CONSTRAINT `postalcode_id`
    FOREIGN KEY (`postal code`)
    REFERENCES `MyPizzeria`.`postalcodes` (`idpostalcodes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastnames` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `type` ENUM("cook", "delivery") NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`idemployees`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `MyPizzeria`.`stores` (`idstores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`delivery_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`delivery_orders` (
  `iddelivery_orders` INT NOT NULL AUTO_INCREMENT,
  `deliverer_id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`iddelivery_orders`),
  INDEX `deliverer_id_idx` (`deliverer_id` ASC) VISIBLE,
  CONSTRAINT `deliverer_id`
    FOREIGN KEY (`deliverer_id`)
    REFERENCES `MyPizzeria`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `placer_name` VARCHAR(45) NOT NULL,
  `order_date_time` TIMESTAMP NOT NULL,
  `type` ENUM("store", "home") NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `order_products_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `placer_name_idx` (`placer_name` ASC) VISIBLE,
  INDEX `order_products_id_idx` (`order_products_id` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `order_products_id`
    FOREIGN KEY (`order_products_id`)
    REFERENCES `MyPizzeria`.`order_products` (`idorder_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `MyPizzeria`.`stores` (`idstores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `delivery_id`
    FOREIGN KEY (`idorders`)
    REFERENCES `MyPizzeria`.`delivery_orders` (`iddelivery_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalcode` SMALLINT NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idclients`),
  INDEX `postalcode_id_idx` (`postalcode` ASC) VISIBLE,
  INDEX `placer_name_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `postalcode_id`
    FOREIGN KEY (`postalcode`)
    REFERENCES `MyPizzeria`.`postalcodes` (`idpostalcodes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `placer_name`
    FOREIGN KEY (`name`)
    REFERENCES `MyPizzeria`.`orders` (`placer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPizzeria`.`products_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyPizzeria`.`products_categories` (
  `idproducts_categories` INT NOT NULL AUTO_INCREMENT,
  `category_of` VARCHAR(45) NOT NULL COMMENT 'Type of product it\'s a category of, for easier querying.',
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`idproducts_categories`),
  UNIQUE INDEX `pizza_id_UNIQUE` (`pizza_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
