package com.api.fortuna.model.domain;

import jakarta.persistence.Id;
import lombok.*;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.concurrent.ThreadLocalRandom;

/**
 *  This class represents a single game in the system.
 *  Uses Lombok annotations for boilerplate code reduction and JPA annotations for database mapping.
 */
@Getter
@NoArgsConstructor
@Document(collection = "games")
public class Game {
    /**
     * The unique identifier for the game. Automatically generated by the database.
     */
    @Id
    private String id;

    /**
     * The unique identifier for the player, taken from the player class during game creation in the service layer and passed through constructor.
     */
    private long playerId;

    /**
     *  First of two dices, named after one of the two temples dedicated to the worship of the name holder of our app.<br><br>
     *  The temple of Fortuna Primigenia was an ancient Roman temple within the sanctuary of Fortuna Primigenia, a religious
     *  complex in Praeneste (now Palestrina, 35 km (22 mi) east of Rome) founded in 204 BC by Publius Sempronius Tuditanus.<br><br>
     *  The temple was dedicated to the goddess Fortuna Primigenia, the exact meaning of whose name is unclear.<br><br>
     *  Parents brought their newly-born first child to the temple in order to improve its likelihood of surviving infancy and perpetuating the family.
     */
    private int primigenia;

    /**
     *  Second of the two dices, named after one of the two temples dedicated to the worship of the name holder of our app.<br><br>
     *  The Temple of Fortuna Muliebris was a temple in ancient Rome dedicated by Proculus Verginius Tricostus Rutilus in 486 BC
     *  to the goddess Fortuna and located at the fourth milestone of the Via Latina.<br><br>
     *  It was founded on behalf of the Roman women who opposed the war of Gaius Marcius Coriolanus and the Volsci against Rome,
     *  commemorating their role in ending Coriolanus' advance on the city.<br><br>
     *  The temple was dedicated in 486 BCE after the war and was formally founded in 493 BCE.<br><br>
     *  Aside from some inscriptions recording restoration work in the Roman imperial period, no remains of the temple exist
     *  and the date it went into disuse is unknown.
     */
    private int muliebris;

    /**
     * Boolean representation of whether the game has been won or not.
     */
    private boolean isWon;

    /**
     * Constructs a new game instance of Player.<br><br>
     *
     * Using the given id, a new game is created. Automatically, separate random values between 1-6 are assigned to each of the dices
     * and victory is determined based on the sum of them.
     *
     * @param playerID The id of the player who has played this game.
     */
    public Game(long playerID){
        this.playerId = playerID;
        this.primigenia = ThreadLocalRandom.current().nextInt(1,7);
        this.muliebris = ThreadLocalRandom.current().nextInt(1,7);
        this.isWon = this.primigenia + this.muliebris == 7;
    }
}