package com.api.fortuna.model.domain;

import com.api.fortuna.model.domain.enums.Roles;
import com.api.fortuna.model.dto.PlayerDTO;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;


/**
 * This class represents a player in the system.
 * Implements UserDetails for integration with Spring Security.
 * Uses Lombok annotations for boilerplate code reduction and JPA annotations for database mapping.
 */
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "players")
public class Player implements UserDetails {

    /**
     * The unique identifier for the player. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idplayers")
    private Long id;

    /**
     * The username of the player.
     */
    @Setter
    private String userPersonalName;

    /**
     * The email of the player.
     * Must be unique.
     */
    @Email
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * The password of the player.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The role of the player.
     * Enum type stored as ordinal in the database.
     */
    @Enumerated(EnumType.ORDINAL)
    private Roles role;

    /**
     * The number of victories the player has achieved.
     */
    private int victories;

    /**
     * The number of games the player has played.
     */
    private int defeats;

    /**
     * The victory rate of the player
     */
    private float winRate;

    /**
     * Required arguments constructor. Annotated with lombok to reduce boilerplate code, but personalized due to needs of the class.
     * @param username of the player.
     * @param email of the player.
     * @param password of the player.
     * @param role of the player
     */
    @Builder
    private Player (String username, String email, String password, Roles role) {
        this.userPersonalName = username;
        this.email = email;
        this.password = password;
        this.role = role;
        this.defeats = 0;
        this.victories = 0;
        calculateWinRate();
    }

    /**
     * Automatically updates the Win Rate variable.
     */
    private void calculateWinRate() {
        int totalGames = victories + defeats;
        this.winRate = totalGames > 0 ? (float) victories / totalGames : 0;
    }

    /**
     * Returns the authorities granted to the player.
     *
     * @return a collection of granted authorities.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return role.getAuthorities();
    }

    /**
     * Returns the username used to register the user.
     *
     * @return The email of the user, which will serve the purpose of username in this implementation.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Returns the password used to register the player.
     *
     * @return the player's password.
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * Indicates whether the player's account has expired.
     *
     * @return true if the account is non-expired, false otherwise.
     */
    @Override
    public boolean isAccountNonExpired() {
        return true; // Accounts are never expired in this implementation
    }

    /**
     * Indicates whether the player is locked or unlocked.
     *
     * @return true if the account is non-locked, false otherwise.
     */
    @Override
    public boolean isAccountNonLocked() {
        return true; // Accounts are never locked in this implementation
    }

    /**
     * Indicates whether the player's credentials (password) have expired.
     *
     * @return true if the credentials are non-expired, false otherwise.
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true; // Credentials are never expired in this implementation
    }

    /**
     * Indicates whether the player is enabled or disabled.
     *
     * @return true if the player is enabled, false otherwise.
     */
    @Override
    public boolean isEnabled() {
        return true; // Players are always enabled in this implementation
    }

    /**
     * Converts player entity to DTO equivalent.
     * @return {@link PlayerDTO} record of the necessary values from the Player.
     */
    public PlayerDTO toDTO (){
        return new PlayerDTO(this.id, this.userPersonalName, this.role, this.winRate);
    }

    /**
     * Victories and defeats are automatically updated.
     * @param isVictory, boolean that expresses if the player has won.
     */
    public void addResult (boolean isVictory){
        if(isVictory){
            this.victories++;
        } else {
            this.defeats++;
        }
        calculateWinRate();
    }

    /**
     * Returns all values to their base values.
     */
    public void cleanResults() {
        this.defeats = 0;
        this.victories = 0;
        this.winRate = 0;
    }
}