-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 12:51:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_dampolla` DEFAULT CHARACTER SET utf8 ;
USE `cul_dampolla` ;

-- -----------------------------------------------------
-- Table `cul_dampolla`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`suppliers` (
  `idsuppliers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NULL,
  `fax` CHAR(11) NOT NULL,
  `nif` CHAR(9) NOT NULL,
  `street` VARCHAR(35) NOT NULL,
  `number` SMALLINT NOT NULL,
  `floor` TINYINT NULL COMMENT 'Not null isn\'t set because some buildings only have door number, lacking the floor.',
  `door` TINYINT NOT NULL,
  `city` VARCHAR(45) NOT NULL COMMENT 'Apparently there\'s a city in the Basque Country the letter count of which reaches up to 39, so I\'m leaving the varchar sized 45 just in case.',
  `country` VARCHAR(56) NOT NULL COMMENT 'Varchar size reflects the possibility of someone giving the full name of the UK.',
  `postalcode` SMALLINT NOT NULL,
  PRIMARY KEY (`idsuppliers`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`glasses` (
  `idglasses` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `prescription_right` DECIMAL(2,2) NOT NULL,
  `prescription_left` DECIMAL(2,2) NOT NULL,
  `frame_type` VARCHAR(8) NOT NULL COMMENT 'A check constraint could also be used to limit the possible inputs to this table, but this is better handled in the code.',
  `frame_color` VARCHAR(15) NOT NULL,
  `glass_color_right` VARCHAR(15) NOT NULL,
  `glass_color_left` VARCHAR(15) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`idglasses`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `cul_dampolla`.`suppliers` (`idsuppliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`registrations` (
  `idregistrations` INT NOT NULL AUTO_INCREMENT,
  `referral_id` INT NULL,
  PRIMARY KEY (`idregistrations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`customers` (
  `idcustomers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `postal_address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registration_id` INT NOT NULL,
  PRIMARY KEY (`idcustomers`),
  INDEX `idregistrations_idx` (`registration_id` ASC) VISIBLE,
  CONSTRAINT `idregistrations`
    FOREIGN KEY (`registration_id`)
    REFERENCES `cul_dampolla`.`registrations` (`idregistrations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary_month` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idemployees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`sales` (
  `idsales` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `glass_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`idsales`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `glasses_id_idx` (`glass_id` ASC) VISIBLE,
  INDEX `seller_id_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cul_dampolla`.`customers` (`idcustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `glasses_id`
    FOREIGN KEY (`glass_id`)
    REFERENCES `cul_dampolla`.`glasses` (`idglasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `cul_dampolla`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
