package cat.itacademy.barcelonactiva.Allegue.Andres.s05.t01.n01.S05T01N01AllegueAndres.model.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@AllArgsConstructor
@ApiModel("Entity for the branches.")
@Builder
@Entity
@Getter
@RequiredArgsConstructor
@Setter
@ToString
@SuppressWarnings("unused")
public class Branch {
    @ApiModelProperty("Primary key id, with the column name \"idbranches\". It will be automatically generated by the database.\n" +
            "Literal name modified to adapt to personal preferences.")
    @Column(name = "idbranches", nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @JdbcTypeCode(SqlTypes.INTEGER)
    private Long id;

    @ApiModelProperty("String variable for the name of each branch. Literal name modified to adapt to personal preferences.")
    @Column(name = "branch_name", nullable = false, unique = true, length = 45)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    private String name;

    @Column(name = "country", nullable = false, length = 45)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    private String country;
}
