package cat.itacademy.barcelonactiva.Allegue.Andres.s04.t02.n01.model.domain;

public enum FruitTypes {
    APPLE,
    ORANGE,
    BANANA,
    MANGO,
    STRAWBERRY,
    GRAPE,
    PINEAPPLE,
    WATERMELON,
    PEACH,
    PEAR,
    CHERRY,
    LEMON,
    LIME,
    BLUEBERRY,
    RASPBERRY,
    BLACKBERRY,
    COCONUT,
    KIWI,
    PLUM,
    APRICOT,
    FIG,
    AVOCADO,
    PAPAYA,
    GUAVA,
    PASSION_FRUIT,
    LYCHEE,
    DATE,
    MELON,
    NECTARINE,
    TANGERINE,
    CLEMENTINE,
    PERSIMMON,
    KUMQUAT,
    CRANBERRY,
    GOOSEBERRY,
    MANGOSTEEN,
    STAR_FRUIT,
    JACKFRUIT,
    DURIAN,
    CANTALOUPE,
    HONEYDEW,
    EGGPLANT, // (Technically a fruit)
    TOMATO,   // (Also technically a fruit)
}